### ISSUE TITLE
Documentation: "run" declaration missing "self"

### ISSUE THREAD

**Issue by keisetsu** [veegee/amqpy#1]
Just getting started with amqpy, but looks good so far.

Running through the simple introductory scripts on rtd, I found that the callback for the Consumer object seems to need `self`. The definition is currently:

    def run(msg: Message):
        print('Received a message: {}'.format(msg.body))
        msg.ack()

but, when run, this fails because `run()` is only expecting `msg`, but gets called as `self.run(msg)` in consumer.py's `_run()` function. I believe the definition of run should be changed to:

    def run(self, msg: Message):
        print('Received a message: {}'.format(msg.body))
        msg.ack()

**Comment by veegee** [comment]
You're absolutely right, that's a documentation typo. Thanks for submitting this!
