### ISSUE TITLE
how mandatory works

### ISSUE THREAD

**Issue by gst** [veegee/amqpy#11]
Hi,

We would like to use the mandatory flag of the basic_publish channel method (to know if a message is well delivered to a queue), but once set to True I don't know what else I need to do ..

do you have some resources / example ? I looked in the code and doc but could not find how this works..

thx.

gst.

**Comment by gst** [comment]
ah, found in the test : 

that's the `returned_messages` attribute of the channel..

but I've nothing in it after I've published with mandatory=True, despite my exchange having no queue bind to it..

an idea ?

**Comment by gst** [comment]
ok I've found completly ; I have to close the channel and then the `returned_message` get the message back.

**Comment by veegee** [comment]
I actually forgot what the specification was regarding this. I'll take a look at and confirm that this is the expected behaviour. I wasn't aware that you had to close the channel to be able to access returned messages.

**Comment by gst** [comment]
Thanks 4 follow up :)

**Comment by gst** [comment]
> I wasn't aware that you had to close the channel to be able to access returned messages.

Actually it is like that in the test, search for `returned_messages` ..

**Comment by gst** [comment]
> Actually it is like that in the test, search for returned_messages ..

https://github.com/veegee/amqpy/blob/master/amqpy/tests/test_channel.py#L330

```python
    def test_basic_return(self, ch, rand_exch):
        ch.exchange_declare(rand_exch, 'fanout')

        msg = Message('funtest message', content_type='text/plain', application_headers={'foo': 7, 'bar': 'baz'})

        ch.basic_publish(msg, rand_exch)
        ch.basic_publish(msg, rand_exch, mandatory=True)
        ch.basic_publish(msg, rand_exch, mandatory=True)
        ch.basic_publish(msg, rand_exch, mandatory=True)
        # calling `close()` will cause all returned messages to be stored in the local queue before closing the channel
        ch.close()

        # 3 of the 4 messages we sent should have been returned
        assert ch.returned_messages.qsize() == 3
```

it's even commented ;)

**Comment by veegee** [comment]
Good find. I remember writing that a while ago, completely forgot about it.

I don't like that interface though. The user should not have to close the channel in order to receive returned messages; they should be made available as soon as they are received. I'll implement a better interface and document it.

**Comment by veegee** [comment]
Update: It actually has nothing to do with `ch.close()`. You can call any method which waits for a server response, such as 
```
try:
    ch.queue_declare('_', passive=True)`
except amqpy.exceptions.NotFound:
    pass
```

or even

```
L:\projects\python\amqpy\amqpy\tests\test_channel.py
and it will work as expected. The purpose of doing this is waiting for the server to send *anything*, and storing them in the `returned_messages` queue. `ch.basic_publish()` doesn't read any data and therefore the channel doesn't get an opportunity to read returned messages from the socket at that point.

Looks like everything is working as expected. I'll update the documentation and tests to reflect this.

Update: It actually has nothing to do with `ch.close()`. You can call any method which waits for a server response, such as 
```
try:
    ch.queue_declare('_', passive=True)`
except amqpy.exceptions.NotFound:
    pass
```

or even

```
        while True:
            try:
                conn.drain_events(0.1)
            except:
                break
```

and it will work as expected. The purpose of doing this is waiting for the server to send *anything*, and storing them in the `returned_messages` queue. `ch.basic_publish()` doesn't read any data and therefore the channel doesn't get an opportunity to read returned messages from the socket at that point.

However, this should be done in a more obvious way, so I'll improve this mechanism shortly.

**Comment by veegee** [comment]
Ok, added a mechanism to replace `Connection.drain_events()`

See: http://amqpy.readthedocs.org/en/latest/amqpy.connection.html#amqpy.connection.Connection.loop
and http://amqpy.readthedocs.org/en/latest/amqpy.channel.html#amqpy.channel.Channel.basic_publish

**Comment by gst** [comment]
Perfect that. Thanks for the clarification & improvement :)

you gonna do a new release with this ?

**Comment by veegee** [comment]
Yes, already uploaded to PyPI: https://pypi.python.org/pypi/amqpy/

Just do `pip install -U amqpy`.

**Comment by gst** [comment]
thx.

**Comment by gst** [comment]
Is it sure that doing loop(0) or drain_events(0) MUST always get the message back from the server (into the returned_messages attribute of the connection) ?

**Comment by veegee** [comment]
Yes, if the server returns messages, then calling that will always place returned messages back into the queue of the appropriate channel. You can set the log level to debug and see exactly what messages are being sent to/from the server.

**Comment by gst** [comment]
because I've done some tests on my side : 

I've setup a publisher, it creates a channel, then declare an exchange & attach queues through/with it. Then my publisher goes waiting for some input.. in the mean time I delete the queues attached to the exchange on the server, then I submit some work to my publisher...

I've so changed my publish side to execute a drain_events(0) after the basic_publish, but I don't ALWAYS get the message back... some gets back, some don't .. in fact, sometimes I get back the message 2 times in `returned_messages`, and sometimes I don't get it back at all, it's all as if it was successfully delivered to a queue (while it wasn't 'cause there is no queue attached to the exchange) in this case.

This is quite problematic to me :s

**Comment by gst** [comment]
could it comes from the rabbit server version I use ? (3.2.4)

**Comment by gst** [comment]
I've installed the latest rabbit server (3.5.3) and same problems..

**Comment by gst** [comment]
hmm.. strange, could be because I'm using multiple threads.. 

In my original setup I'm effectively using multiple threads to do my publish job, using the same connection & channel but my publish method (in which I do basic_publish(mandatory=True) then drain_events(0) then I check `returned_message`) is protected by a lock..  So I was hoping it wouldn't impact.. 

Now I've changed my setup to only use one one publish thread and there I finally got back every message successfully.. 

strange.. :s

**Comment by gst** [comment]
If I create a new channel for each publish and close it after it's also ok.

**Comment by veegee** [comment]
There may be multiple things going on here. You have to make sure that there's no more than one thread operating on any given channel.

From `method_io.py::MethodWriter::write_method()`:
```    This method is thread safe only if the `channel_id` parameter is unique across concurrent
        invocations. The AMQP protocol allows interleaving frames destined for different channels,
        but not within the same channel. This means no more than one thread may safely operate on
        any given channel.```

**Comment by gst** [comment]
I was rather sure of me but I'm gonna triple verify all that ;)

**Comment by gst** [comment]
have done some verifications / simplifications on my side, and I'm quite confident of me (that there seems to be a problem with amqpy, single channel, and multiple threads (but not doing reads or writes simultaneously)) :s

what if I create a test case showing my current problem ?  would you consider investigating it ?

**Comment by veegee** [comment]
I will definitely investigate it. Can you send me your current code? You can use a gist or something like that to paste it.

**Comment by veegee** [comment]
You can also open a new issue specific to this case, and we can discuss in the new issue.

**Comment by gst** [comment]
ok doing that
