### ISSUE TITLE
possible counter problem with consumer dedicated threads

### ISSUE THREAD

**Issue by gst** [veegee/amqpy#13]
in https://github.com/veegee/amqpy/blob/master/amqpy/consumer.py#L92

```python
    def _run(self, msg):
        self.run(msg)
        self.consume_count += 1

    def start(self, msg):
        if self.use_thread:
            t = Thread(target=self._run, args=(msg,), name='consumer-{}'.format(self.consumer_tag))
            t.start()
        else:
            self._run(msg)
```

if the use_thread is activated, then the self.consume_count could lose some counts : 

```idle
>>> counter = 0
>>> def r(N):
	global counter
	for _ in range(N):
		counter += 1
>>> import threading
>>> threads = [ threading.Thread(target=r, args=(100000,)) for i in range(10) ]
>>> x = [ t.start() for t in threads ]
>>> counter
921570  
>>>  # should have been 10 * 100000
```

**Comment by veegee** [comment]
Yeah, I should remove that. That's not the way consumers should be used anyway. The correct way is to use one consumer per channel and one consumer per thread.

**Comment by gst** [comment]
> That's not the way consumers should be used anyway.

I would say that's it's not the *best* way effectively, and I'm mostly agree with you.
Then the use_thread flag of the consumer class, and all this code around it, should be simply removed, isn't it ?

**Comment by veegee** [comment]
Yes, the use_thread mechanism will be removed. It's something I've wanted to do before releasing v1.0.0 stable. The best way is to manage threading yourself instead the library offering its own mechanism.
