### ISSUE TITLE
mandatory and channel.returned_messages bad behavior ?

### ISSUE THREAD

**Issue by gst** [veegee/amqpy#14]
see :  https://gist.github.com/gst/ad5dff15e2fe37e9b3dc

Basically:

(If I do correctly use the feature) it so seems that returned_messages is not always correctly handled..

running the gist can give you different results from one run to another, example  : 

bad multiple returned: ['0:1', '0:3']
bad some not_returned: ['0:0', '0:2', '0:4']

another:
bad some not_returned: ['0:0', '0:1', '0:2', '0:3', '0:4']

sometimes it succeed correctly..

But if re-create / instantiate the channel in my_publish, and call its close() instead of conn.loop(0), then it always always succeed (all messages are correctly returned only once)  **EDIT**: damn even not... just checked with more threads and more loops and got : 
bad multiple returned: ['0:58']
bad some not_returned: ['0:57']

**Comment by gst** [comment]
in fact, even with a single thread (n_threads=1), and with the `conn.loop(0)` (0, not 0.000..1), then most messages are not seen back..

**Comment by gst** [comment]
Think I've maybe found : 

I have to wrap the basic_publish(..) between channel.tx_select() and channel.tx_commit() and THEN I get always (really this time) all the messages back correctly.. with the close() way as well as with the conn.loop(0) ..

can you confirm that this is required to be completely sure to get back, I mean in a "synchronously/reliable" way, all messages with mandatory=True ?

**Comment by gst** [comment]
and after thinking about it, it seems perfectly legit :

To be sure to get a message back we have to use some kind of transaction, cause otherwise it would not be guaranteed when the message would be back at the channel level ..

**Comment by gst** [comment]
the `conn.loop(0)` is even not necessary with the transaction enabled, `tx_commit()` seems to take care of what need to be..

**Comment by veegee** [comment]
Ok, looking into it now.

**Comment by veegee** [comment]
I ran this multiple times with 100 threads, I'm still not seeing any errors

**Comment by gst** [comment]
Ho boy.. there is an error in my gist (even though it appear to just work on my last explained version).. but that just change (not very well) the results.. looking into that..

**Comment by veegee** [comment]
Ok solved your problem. Where you check call `conn.loop()`, call it with a larger wait time like `conn.loop(0.01)` or even 0.1 to allow the server some time. If you don't allow the server to process it and return it, two things can happen like you are seeing:

1. The server may not have enough time on the first cycle to send any message, in which case your program will see it as a "missed" message.
2. By the next cycle, the server has had enough time, and therefore will have enqueued two messages (the first one being the missed message). In this case, your program will see it as "multiple messages being returned".

If you simply allow the server slightly more time to return the messages, everything works perfectly. Please confirm.

**Comment by gst** [comment]
Yeah ;) but what we don't want to do is to have to use such an "hard-coded" timeout on the conn.loop() call to get the message back ..

in fact, we could (nearly over-)load a rabbit server, and then the 0.01 (or even 0.1) would be not enough for it to actually process the message and return it as expected...

the use of the transaction mode, apparently makes that all for us, and afaisee, at a better speed..

**Comment by gst** [comment]
> and afaisee, at a better speed..

once you put enough entropy/parallelism on it, but it will(should) be always reliable..

**Comment by gst** [comment]
the fact is that : I want to be notified, and as soon as possible but in an "absolute way", if a message can't be delivered to a queue (because none is attached to the exchange I'm publishing on).
The tx mode, used here, makes sure of that, even if the client and/or the server are totally overloaded (but still responsive) :)  otherwise well, all bets are open ;)

**Comment by gst** [comment]
> The tx mode, used here, makes sure of that

*here* : https://gist.github.com/gst/b8069aa55ae56be707bc

on my station it takes ~30 seconds to complete, not that bad given the load.. ;)

**Comment by veegee** [comment]
In conclusion, there is no bug here and it is performing as expected. The only way to check for returned messages is to poll it. You can use a `poll()` mechanism on the socket to wait for messages. I don't think using transactions guarantees anything, it just gives the server more time to process the message. You could also use the RabbitMQ publish acknowledge mode for the same effect; call `ch.confirm_select()` once to put the channel in publish ack mode, and every call to `basic_publish()` will wait for a response from the server.

**Comment by gst** [comment]
We are both right :)
What I want to emphasize is that calling conn.loop(0.X) **could be** not enough (if the server (and/or client?) is too slow), and you simply would miss the message back (just give it more time / sleep longer waiting it .. ok, but how long ??) . The only reliable way to get that message back - "directly after it's published" - is to use a transaction (don't know if there is an amqpy level timeout which would make it possible to abort/timesout such a tx_commit() though..).

**Comment by gst** [comment]
To conclude for my part : there could be a documentation miss-understanding, as it is : we seem to understand that a "simple" conn.loop(*some_enough_time*) is enough to get a message back if no queue is attached to the exchange we are publishing on (and we used the mandatory flag on publish ofcourse). but it is not always, whatever is the *some_enough_time* .. (for a certain load)

**Comment by veegee** [comment]
I would not recommend using transactions for this purpose though. RabbitMQ publish ack is more appropriate, see here: https://www.rabbitmq.com/confirms.html

Although transactions will send `basic.return` before `tx.commit-ok`, as stated here: https://www.rabbitmq.com/semantics.html, they may be more CPU/memory intensive than publish confirm mode. 

You may need to benchmark to be sure.

**Comment by gst** [comment]
Will need to give a look on that, but later ;) a quick look could have raised a warn on my side, not sure  I completely manage all the ins&outs with the routable & unroutable messages and how to best handle them.. you could have a point ;)

**Comment by gst** [comment]
my points in https://github.com/veegee/amqpy/issues/14#issuecomment-123128187 still stands ;)

**Comment by gst** [comment]
> I would not recommend using transactions for this purpose though. RabbitMQ publish ack is more appropriate, see here: https://www.rabbitmq.com/confirms.html
> You may need to benchmark to be sure. But either one of those will suit your needs.

Tried with Channel.confirm_select() (before the basic_publish()) instead of the tx_select+commit.

and same results, say 5-10% faster with the confirm_select()..

not sure which one is the best for me to use.. but I understand that confirm_select() could be better eventually.
