### ISSUE TITLE
Message body are bytes..

### ISSUE THREAD

**Issue by gst** [veegee/amqpy#18]
When I publish some message through the rabbitmq admin interface (localhost:15672), the message body as received in my consumer is bytes.. 

While for messages I've published with a regular publisher the message body got in the consumer is  text/str ..

is it expected ?

**Comment by veegee** [comment]
You have to set the Content-Type header appropriately. If it is set correctly, the library auto-decodes it. You can disable auto decoding if you like: http://amqpy.readthedocs.org/en/latest/amqpy.channel.html?highlight=auto_decode

**Comment by gst** [comment]
NB: apparently it's only the *content_encoding* **property** (not header) that was needed to be set in my case.

**Comment by veegee** [comment]
Ah, sorry, you're right. It's the `content_encoding`: http://amqpy.readthedocs.org/en/latest/amqpy.message.html#amqpy.message.Message.__init__
