### ISSUE TITLE
Channel.basic_publish() vs Channel.basic_publish_confirm()

### ISSUE THREAD

**Issue by gst** [veegee/amqpy#19]
I don't see how useful is actually `basic_publish_confirm()`, except that it explicitly checks that the channel has been put in confirm mode..

But in my opinion this shouldn't be needed, if one wants to use channel confirm mode then he anyway has to call `channel.confirm_select()` and then he calls `basic_publish()` (which notices the channel is in confirm mode and wait for the ack as necessary) and voilà, that's all. 

So if one wants to use the confirm mode but does not call confirm_select() then it's his fault.. and it's not to amqpy to provide a way (basic_publish_confirm) to verify that.

So in my opinion we could simply drop `basic_publish_confirm()`.  Simpler, better ;)

wdyt ?

**Comment by gst** [comment]
maybe first make it a deprecated method and then in a later version remove it.

**Comment by veegee** [comment]
You're right, it should be removed. Doesn't need to be deprecated, the version numbers are still below 1.0.0 so the API isn't guaranteed stable yet.

**Comment by gst** [comment]
done in https://github.com/veegee/amqpy/pull/20
