### ISSUE TITLE
possible bad assumption with abstract_channel._wait_method()

### ISSUE THREAD

**Issue by gst** [veegee/amqpy#25]
there is in that function :  
`if allowed_methods is None` 

but I think that case can never happen.
The only code path were (I think) it could have occurred is from this same function, at its end : 
```python
            if ch_id == 0:
                self.connection.wait()

# with:

    def wait(self, method=None):
        """Wait for the specified method from the server

        :param method: method to wait for, or `None` to wait for any method
        :type method: spec.method_t or None
        """
        m = self._wait_method([method])
        return self.handle_method(m)
```

But as you see: in that case (`method==None`)  then `_wait_method()` is so called with `[None]` ; not `None` ..

So in case of method is `None` here then `_wait_method()` should be called with `None` as well, not `[None]`..

Am I right ? / do you agree ?

**Comment by veegee** [comment]
VERY nice catch! You're right, this is bad logic. Will fix.
