### ISSUE TITLE
adapt test for interrupt by signal for python3.5

### ISSUE THREAD

**Issue by gst** [veegee/amqpy#26]
https://docs.python.org/3.6/whatsnew/3.5.html#pep-475-retry-system-calls-failing-with-eintr

> Note that the system call is only retried if the signal handler does not raise an exception.

So I think you need to raise some exception in the signal handler below :

(from: https://github.com/veegee/amqpy/blob/master/amqpy/tests/test_connection.py#L119)
```
def test_interrupted(self, conn):
        """Make sure to get InterruptedError if a read was interrupted
        """

        def sig_handler(sig, frame):
            pass
```

otherwise I think that test will fail in python3.5..

**Comment by veegee** [comment]
Thanks for this, I will review this tomorrow.

**Comment by veegee** [comment]
I just realized that this has been added.
