### ISSUE TITLE
basic_get is non-blocking

### ISSUE THREAD

**Issue by nmoehrle** [veegee/amqpy#9]
I have currently the problem that I use a queue as task queue for a cluster and each consumer should only get one task at a time and simply wait/block if no tasks are available. A blocking basic_get would solve this problem and I could not come up with an other solution. According to http://www.rabbitmq.com/amqp-0-9-1-quickref.html the amqp method basic.get should be synchronous, probably to enable such use cases.

**Comment by veegee** [comment]
You're using it incorrectly, and synchronous/asynchronous in this context doesn't have anything to do with blocking/nonblocking basic-get. For your purpose, the right way to do it is create a "queue consumer" (see consumer example) and set the QoS settings to dispatch 1-10 messages to each consumer at a time. 

The basic-get function in this library is behaving according to AMQP 0.9.1 specifications.
